# DTSC670: Foundations of Machine Learning Models

## Assignment 2: California Housing Prices Data Manipulation

### Name:


## CodeGrade
Note that this assignment will be automatically graded through CodeGrade and you will have unlimited submission attempts.  When submitting to CodeGrade, your notebook should be named `assignment2.ipynb` and there should be no errors in the file or CodeGrade will not be able to grade it.  Before submitting, I suggest that you restart your kernel and attempt to run all cells again to ensure that there will be no errors when CodeGrade runs your script.  

## Details

The purpose of this assignment is to hone your data wrangling skills.  It has been estimated that up to 80% of a Data Scientist's role is data cleaning and manipulation tasks to get the data ready for modeling/machine learning.  Your task for this assignment is to perform the data preparation steps as instructed below. 

In the "End-to-End Machine Learning" module, you will be working with the California Housing Prices dataset that is based on data from the 1990 California census.  This dataset is often used to practice building a model to predict housing prices.  I have downloaded the original data and made various changes to it.  Your job will be to clean and manipulate the data to get it back to the proper format.  

*Note that your final dataset will <b>not</b> match the dataset that we will use in the class module.  This is on purpose so that students cannot download the data from various online sources and pass it off as their "cleaned" data.* 

### Files and Data Dictionary

The files that you will be working with, and that can be found on Brightspace, are:

- <u>long_lat.csv</u>: longitude and latitude coordinates for all instances
- <u>cal_housing_low.csv</u>: instances with median house values in the lower 25% percentile
- <u>cal_housing_medium.csv</u>: instances with median house values between the lower and upper percentiles
- <u>cal_housing_high.csv</u>: instances with median house values in the upper 75% percentile
- <u>ocean_proximity.csv</u>: longitude and latitude coordinates along with their corresponding category 

The data dictionary for the columns in the files are:

- <u>id</u>: unique ID number for the respective district (also called block groups)
- <u>longitude</u>: longitude coordinates for the respective district
- <u>latitude</u>: latitude coordinates for the respective district
- <u>state</u>: US state for the respective district 
- <u>medianHouseValue</u>: median house value in the respective district (this will be the target or response variable)
- <u>housingMedianAge</u>: median house age in the respective district
- <u>totalBedrooms</u>: total bedrooms for all houses in the respective district
- <u>totalRooms</u>: total number of rooms for all houses in the respective district
- <u>households</u>: total households for all houses in the respective district
- <u>population</u>: total population for all houses in the respective district
- <u>medianIncome</u>: median income for households in the respective district
- <u>ocean_proximity</u>: categorical variable for each respective longitude and latitude pair  

### Data Cleaning
In order to clean the data, you will need to perform the following steps, although not necessarily in this order:
- Make sure that your notebook is organized and that you include specific comments that explain your code.  Assignments will be manually checked at the end of the course and points may be deducted for insufficient comments. (see Assignment Rubric)
- Use only base Python, Pandas, or NumPy for this assignment.  
- Combine the files together, as appropriate, so that you have one final DataFrame
- The final DataFrame must be named `housing`
- Sort the final `housing` DataFrame by `id` in ascending order
- Drop any rows with a missing value for the `medianHouseValue` column
- Fill any rows with a missing value for the `housingMedianAge` column with the median value for that column
- Drop the `state` column since it doesn't offer any added value
- In order to match the data that will be worked on in class, you will make the following changes to the values:
  - Scale the `medianIncome` to express the values in $10,000 of dollars (example: `150000` will become `15`, `30000` will become `3`, `15000` will become `1.5`, etc)
  - In your textbook, it discusses that the median income values have been capped on both the lower and upper ends.  In order to recreate this data, change any values in the `medianIncome` column that are `0.4999` or lower to `0.4999` and change any values that are `15.0001` and higher to `15.0001`.  This step should be done after the previous step.  Take a look at [this stackoverflow answer](https://stackoverflow.com/questions/38876816/change-value-of-a-dataframe-column-based-on-a-filter) if you need help with this step.
  - Revert the `medianHouseValue` back to actual dollars (example: `150` will become `150000`, `300` will become `300000`, etc)
- Update the column names and column order as shown below to match the data from the module:
  - longitude
  - latitude
  - housing_median_age
  - total_rooms
  - total_bedrooms
  - population
  - households
  - median_income
  - median_house_value
  - ocean_proximity
- Change all columns to a float data type except for the `ocean_proximity` column.  The `ocean_proximity` column should remain a string/object data type (do not update this to a categorical data type since that will be done later when working with the module data).
- Reset the DataFrame index so that it goes from `0` to `n-1`, where `n` is the number of rows in your DataFrame

In [1]:
# standard imports
import pandas as pd
import numpy as np

# Do not change this option; This allows the CodeGrade auto grading to function correctly
pd.set_option('display.max_columns', 20)

In [2]:
# Insert as many cells as you need, but be sure your code is very neat and very well documented.

# Loading the different Sheets

In [3]:
#Import Data
long_lat = pd.read_csv('long_lat.csv')
cal_housing_low = pd.read_csv('cal_housing_low.csv')
cal_housing_med = pd.read_csv('cal_housing_medium.csv')
cal_housing_high = pd.read_csv('cal_housing_high.csv')
ocean_proximity = pd.read_csv('ocean_proximity.csv')

# Taking a look at the different values and columns in each of the sheets

In [4]:
long_lat.head(1)

   id  longitude  latitude
0   1    -122.23     37.88

In [5]:
cal_housing_low.head(1)

,id,state,medianHouseValue,housingMedianAge,totalBedrooms,totalRooms,households,population,medianIncome
0,23,CA,113.903,NaN,543.0,2438.0,481.0,1016.0,17250.0

In [6]:
cal_housing_med.head(1)

,id,state,medianHouseValue,housingMedianAge,totalBedrooms,totalRooms,households,population,medianIncome
0,8,CA,241.403,53.0,688.0,3104.0,648.0,1161.0,31200.0

In [7]:
cal_housing_high.head(1)

,id,state,medianHouseValue,housingMedianAge,totalBedrooms,totalRooms,households,population,medianIncome
0,1,CA,452.603,45.0,131.0,884.0,130.0,323.0,83252.0

In [8]:
ocean_proximity.head(1)

  ocean_proximity  longitude  latitude
0        NEAR BAY    -122.23     37.88

In [11]:
#ocean_proximity['ocean_proximity'].value_counts()

# Merge all 5 sheets together

In [12]:
housing1 = long_lat.merge(cal_housing_low) #merge long_lat with cal_housing_low

In [13]:
housing2 = long_lat.merge(cal_housing_med) #merge long_lat with cal_housing_med

In [14]:
housing3 = long_lat.merge(cal_housing_high) #merge long_lat with cal_housing_high

In [15]:
housing = pd.concat([housing1, housing2, housing3],ignore_index = True) # combine housing1,2 and 3 into 1 sheet with all day except Ocean Proximity

In [16]:
housing = housing.merge(ocean_proximity, on = ['longitude', 'latitude']) #merge housing with ocean_proximity data

In [17]:
housing = housing.sort_values('id', ascending = True) #sort DF by id in ascending order

In [19]:
#housing['ocean_proximity'].value_counts()
housing['ocean_proximity'] = housing['ocean_proximity'].values.astype(str)

# Drop NA from medianHouseValue column

In [20]:
housing['medianHouseValue'].isna().sum() #how many na values are in the medianHouseValue column

918

In [21]:
housing = housing.dropna(subset = ['medianHouseValue']) #dropping na values from medianHouseValue column

# Fill NA values in housingMedianAge with Median value

In [22]:
housing['housingMedianAge'].isna().sum() #how many NA values are in housingMedianAge column

1166

In [23]:
housing['housingMedianAge'].median() #what is the median housingMedianAge?

31.0

In [24]:
housing['housingMedianAge'] = housing['housingMedianAge'].fillna(housing['housingMedianAge'].median()) #fill NA with median value

In [25]:
# housing['housingMedianAge'].isna().sum() - resulted in 0 so all NA were filled

# Drop the state column from housing DF

In [26]:
housing = housing.drop(columns = 'state')

# Change number format for medianIncome and medianHouseValue

In [27]:
housing['medianIncome'] = housing['medianIncome'].div(10000).round(4) #scaling down medianIncome by a factor of 10000

In [28]:
# establishing cap values at 15.0001 and .4999
housing.loc[housing['medianIncome'] <= .4999] = .4999
housing.loc[housing['medianIncome'] >= 15.0001] = 15.0001

In [29]:
# revert medianHouseValue back to actual dollars
housing['medianHouseValue'] = housing['medianHouseValue']*1000

# Update Column names and order

In [30]:
rename_dic = {'longitude' : 'longitude', 
          'latitude' : 'latitude',
          'housingMedianAge' : 'housing_median_age',
          'totalRooms' : 'total_rooms',
         'totalBedrooms' : 'total_bedrooms',
         'population' : 'population',
         'households' : 'households',
         'medianIncome' : 'median_income',
         'medianHouseValue' : 'median_house_value',
         'ocean_proximity' : 'ocean_proximity'}
housing.rename(columns=rename_dic, inplace = True)

In [31]:
# reorder the columns
housing = housing[['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population',
                'households','median_income', 'median_house_value', 'ocean_proximity']]

# Change all columns to float datatype except ocean_proximity

In [32]:
housing[['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 
         'median_income', 'median_house_value']] = housing[['longitude', 'latitude', 'housing_median_age', 'total_rooms', 
                                                            'total_bedrooms', 'population', 'households','median_income', 
                                                            'median_house_value']].values.astype(float)

In [35]:
housing.dtypes # - Datatypes were successfully changed to float64

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

# Reset dataframe index starting from 0 to n-1

In [34]:
housing = housing.reset_index(drop = True)
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,45.0,884.0,131.0,323.0,130.0,8.3252,452603.0,NEAR BAY
1,-122.22,37.86,23.0,7103.0,1108.0,2403.0,1141.0,8.3014,358502.0,NEAR BAY
2,-122.24,37.85,53.0,1468.0,193.0,500.0,180.0,7.2574,352104.0,NEAR BAY
3,-122.25,37.85,55.0,1278.0,236.0,558.0,222.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,54.0,1628.0,282.0,568.0,262.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,28.0,1665.0,374.0,847.0,332.0,1.5603,78101.0,INLAND
20636,-121.21,39.49,18.0,701.0,154.0,360.0,114.0,2.5568,77102.0,INLAND
20637,-121.22,39.43,19.0,2257.0,488.0,1007.0,437.0,1.7000,92301.0,INLAND
20638,-121.32,39.43,21.0,1864.0,412.0,744.0,349.0,1.8672,84701.0,INLAND
20639,-121.24,39.37,18.0,2787.0,616.0,1387.0,532.0,2.3886,89401.0,INLAND